// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXVnuNVSqB70l0dFO5CHz6KBElqapjqU',
    appId: '1:301588372983:web:8132bbe1ef62f3558862f2',
    messagingSenderId: '301588372983',
    projectId: 'swecom-app',
    authDomain: 'swecom-app.firebaseapp.com',
    storageBucket: 'swecom-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZx7eiZLqb9QIcdH5xSzyB4U-uHicOfw',
    appId: '1:301588372983:android:60ccfc5c37f13f778862f2',
    messagingSenderId: '301588372983',
    projectId: 'swecom-app',
    storageBucket: 'swecom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LjyPYZGbuyLfsU7qK_846ydK9lYVFpk',
    appId: '1:301588372983:ios:65f5ab27195a3c0b8862f2',
    messagingSenderId: '301588372983',
    projectId: 'swecom-app',
    storageBucket: 'swecom-app.appspot.com',
    iosBundleId: 'com.swecom.app.swecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LjyPYZGbuyLfsU7qK_846ydK9lYVFpk',
    appId: '1:301588372983:ios:65f5ab27195a3c0b8862f2',
    messagingSenderId: '301588372983',
    projectId: 'swecom-app',
    storageBucket: 'swecom-app.appspot.com',
    iosBundleId: 'com.swecom.app.swecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRXVnuNVSqB70l0dFO5CHz6KBElqapjqU',
    appId: '1:301588372983:web:fe2aa72d41ef052a8862f2',
    messagingSenderId: '301588372983',
    projectId: 'swecom-app',
    authDomain: 'swecom-app.firebaseapp.com',
    storageBucket: 'swecom-app.appspot.com',
  );
}
